#!/usr/bin/env python3 
import argparse
import re
RED = "\u001b[31m"
parser = argparse.ArgumentParser()
parser.add_argument("regex", help="regular expression to search for",
                    type=str)
parser.add_argument("file", help="path to the file you want to scan",
                    type=str)
args = parser.parse_args()

def reInLine(regex, i, line):
    match = regex.search(line)
    if match:
        ms = match.start()
        me = match.end()
        return (i, line[0:ms] + colorize(line[ms:me], RED) + \
               reInLine(regex, i, line[me:])[1])
    return (i, line)

def colorize(string, color):
    return color + string + "\u001b[0m"

with open(args.file, "r") as f:
    content_raw = f.read()
    content = content_raw.split("\n")
    regex = re.compile(args.regex)
    result = [reInLine(regex, i, line)
              for i, line in enumerate(content) if regex.search(line)]
    print("\n".join([colorize(str(i+1) + ": ", RED) + line
          for i, line in result]))
